# Generated by Django 2.1.2 on 2019-06-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('identity', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('age', models.IntegerField(default=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('cellphone', models.CharField(default='', max_length=12)),
                ('pay_id', models.CharField(default='', max_length=30)),
                ('zone', models.CharField(default='', max_length=20)),
                ('introduction', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('courseName', models.CharField(default='abc', max_length=256)),
                ('time', models.DateTimeField()),
                ('peopleNum', models.IntegerField(default=1)),
                ('courseContent', models.TextField()),
                ('state', models.IntegerField()),
                ('tag', models.TextField()),
                ('type', models.CharField(max_length=256)),
                ('picture1', models.ImageField(null=True, upload_to='')),
                ('picture2', models.ImageField(null=True, upload_to='')),
                ('picture3', models.ImageField(null=True, upload_to='')),
                ('picture4', models.ImageField(null=True, upload_to='')),
                ('picture5', models.ImageField(null=True, upload_to='')),
                ('picture6', models.ImageField(null=True, upload_to='')),
                ('picture7', models.ImageField(null=True, upload_to='')),
                ('picture8', models.ImageField(null=True, upload_to='')),
                ('picture9', models.ImageField(null=True, upload_to='')),
                ('teacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='course_order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('state', models.CharField(choices=[('C', 'Complete'), ('UP', 'Unpaid'), ('N', 'Not finish'), ('R', 'Refund')], max_length=4)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.course')),
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_order',
            },
        ),
        migrations.CreateModel(
            name='recruitment_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('isDelete', models.BooleanField(default=False)),
                ('courseContent', models.TextField()),
                ('tag', models.TextField()),
                ('type', models.CharField(default='abc', max_length=256)),
                ('picture1', models.ImageField(null=True, upload_to='')),
                ('picture2', models.ImageField(null=True, upload_to='')),
                ('picture3', models.ImageField(null=True, upload_to='')),
                ('picture4', models.ImageField(null=True, upload_to='')),
                ('picture5', models.ImageField(null=True, upload_to='')),
                ('picture6', models.ImageField(null=True, upload_to='')),
                ('picture7', models.ImageField(null=True, upload_to='')),
                ('picture8', models.ImageField(null=True, upload_to='')),
                ('picture9', models.ImageField(null=True, upload_to='')),
                ('stuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_info',
            },
        ),
    ]
