# Generated by Django 2.1.2 on 2019-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recruitment_info',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='salary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='scope',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='peopleNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='recruitmentName',
            field=models.CharField(default='abc', max_length=256),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='salary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='scope',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recruitment_info',
            name='teaching_age',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseContent',
            field=models.TextField(default='abc'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recruitment_info',
            name='courseContent',
            field=models.TextField(default='abc', max_length=256),
        ),
        migrations.AlterField(
            model_name='recruitment_info',
            name='tag',
            field=models.TextField(default='abc'),
        ),
    ]
